### ISSUE TITLE
IfcObjectDefinition.isDecomposedBy is not a Set of IfcRelAggregates

### ISSUE THREAD

**Issue by giovannivelludo** [pipauwel/IFC.JAVA#1]
The type of [IfcObjectDefinition.isDecomposedBy](https://github.com/pipauwel/IFC.JAVA/blob/master/src/main/java/com/buildingsmart/tech/ifc/IfcKernel/IfcObjectDefinition.java#L61) in this repository is IfcRelAggregates, but it's supposed to be a Set of IfcRelAggregates [according to the IFC version 4.1 specification](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifckernel/lexical/ifcobjectdefinition.htm) (and even earlier version as far as I can tell).
I'm trying to fix this myself both in that class and in IfcParser but I'm getting all kinds of errors when doing `mvn clean install`, so I figured I'd post about it here in the meantime.

**Comment by pipauwel** [comment]
Apologies for never reacting to this. I somehow totally missed this issue; I did not know it was there. And I had to leave this code behind for a long while. The issue dates from a period when this code was not fully finished yet. This should be better now - mvn install works fine here in any case. I have modified the definition of IfcObjectDefinition.isDecomposedBy so that it is a Set of IfcRelAggregates now. Thank you for posting this.
